FROM python:3.12-slim

WORKDIR /app

RUN apt update && \
    apt install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . /app
WORKDIR /app
RUN uv sync --locked

CMD ["uv", "run", "app.main"]
